### ISSUE TITLE
Log file clutter: MissingMethodException: Method not found: 'VesselView.VesselViewer.drawCall'.

### ISSUE THREAD

**Issue by Neouni** [KitwareMedical/VesselView#101]
Plugin window doesn't seem to draw but rasterpropmonitor version works fine
But even when the plugin window is not open vesselview seems to generate around 30 errors per second while controlling an object.
Doesn't matter if the object has a cockpit affected by rasterpropmonitor, remote controlled generated the same.

[EXC] MissingMethodException: Method not found: 'VesselView.VesselViewer.drawCall'.

Probably a small typo somewhere

(Using the version included with rasterpropmonitor 19.3)

**Comment by vovythevov** [comment]
Hey Neouni,

I think you have us confused with another repository.. This repository's VesselView is a desktop application for medical imaging, specialized towards vessels, as in blood vessels, not space ships :) 

We do appreciate your contribution, but I think the developer of the kerbal space program vessel viewer might be even more interested (see this repository here: https://github.com/PeteTimesSix/VesselViewer).

Thanks, Johan

P.S.: I am closing this issue since I don't think it's intended for us.
