### ISSUE TITLE
Change blue link to a more gray-ish/white-ish blue

### ISSUE THREAD

**Issue by vovythevov** [KitwareMedical/VesselView#66]
See color RBG(122 155 196)

**Comment by vovythevov** [comment]
Also, see if something can be done for the logos (in the same idea)

**Comment by matthieuheitz** [comment]
Could you guide me to where I should modify things ?
It seems that in the QML, we want to change the Palette.text.
I tried to open the qml file with QtDesigner, but it tells me that qmlpuppet is missing.
I only have qml2puppet, I did a symlink to it, called qmlpuppet, and it works, but I have some errors like "Invalid URL. (M6)" at multiple lines, apparently it doesn' like the URL that begins with ":/" ...
Do you usually edit the qml files with QtDesigner ?

**Comment by vovythevov** [comment]
I edit the qml files with qt creator.
To edit the color of the hyperlink, you probably need to edit the style.
Right now, we depend on the slicer's dark style. We might want to create
our own style. I encourage you to look up qt palette and style and how they
work.

On Friday, February 6, 2015, Matthieu Heitz <notifications@github.com>
wrote:

> Could you guide me to where I should modify things ?
> It seems that in the QML, we want to change the Palette.text.
> I tried to open the qml file with QtDesigner, but it tells me that
> qmlpuppet is missing.
> I only have qml2puppet, I did a symlink to it, called qmlpuppet, and it
> works, but I have some errors like "Invalid URL. (M6)" at multiple lines,
> apparently it doesn' like the URL that begins with ":/" ...
> Do you usually edit the qml files with QtDesigner ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KitwareMedical/VesselView/issues/66#issuecomment-73141886>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matthieuheitz** [comment]
And you don't get any errors on the URLs when you edit it ?

**Comment by matthieuheitz** [comment]
To be able to open WelcomeScreen.qml, I have to:
- Change all the URLs that start with ":/" to "/"
- Comment any imperative code, because otherwise, I can't edit anything
And even after that, the layouts are all messed up.

Which version of Qt and Qt Creator do you use ?
I've tried with Qt Creator 3.1.2 (based on Qt 5.3.1), and with Qt Creator 3.0.1 (based on Qt 5.2.1), and none of them works properly.

The issue for the imperative code is already reported to Qt, but apparently it has been closed last May... : http://stackoverflow.com/questions/21325456/qml-imperative-code-not-supported.
The 2 versions of Qt Creator that I have were built later than May.
